### ISSUE TITLE
Processed and saved output differ

### ISSUE THREAD

**Issue by umara-Nissar** [paoloinglese/DESI_MSI_recal#1]
@paoloinglese Dear Paolo,
In the data generated with the DESI_MSI_recal there is an offset of pixels in my sample tissues between the processed and resulting mask (saved output). If you could please help me with this issue. Please find the attached slide with an example. 
[Segmentation_roi.pptx](https://github.com/paoloinglese/DESI_MSI_recal/files/9696464/Segmentation_roi.pptx)

**Comment by piplus2** [comment]
Hi! I'll have a look at that.

**Comment by umara-Nissar** [comment]
Hey Paolo,
Thank you!

**Comment by piplus2** [comment]
Have you checked if the actual ROI csv is identical to the plotted mask?

**Comment by umara-Nissar** [comment]
Attached is the ROI overlap and you can see that the plotted mask is already shifted. As you can see that the two pixels on the left edge where the mask is at y = 5, while the empty pixel are at y = 4.
![roi_overlap](https://user-images.githubusercontent.com/58521260/193567841-a99d3258-25f2-4b92-8099-d349f95ae9bb.png)

**Comment by piplus2** [comment]
Do you observe the same discrepancy if you zoom in or out in the gui?

**Comment by umara-Nissar** [comment]
Hey Paolo,
Zooming in and out in the GUI does not reproduce the shift, but when the save button is clicked the rois shift. Also zooming out too much bins the pixels together.

**Comment by piplus2** [comment]
Can you please try with the version in the testing branch?

https://github.com/paoloinglese/DESI_MSI_recal/tree/testing

**Comment by piplus2** [comment]
Any update @umara-Nissar ?

**Comment by umara-Nissar** [comment]
Hey Paolo, 
I tried it. It is giving an error 
RuntimeWarning: invalid value encountered in divide values = (values / np.max(values) * 255).astype(np.uint8)

**Comment by piplus2** [comment]
You can ignore that warning. Have you got the results?

**Comment by umara-Nissar** [comment]
It is not generating results. It is giving an error that only one set of pixels was selected

**Comment by piplus2** [comment]
Can you share the dataset?

**Comment by umara-Nissar** [comment]
I have emailed you the data files.

**Comment by piplus2** [comment]
Can you please try with the testing branch? I made some changes and it seems to work with your data now.

**Comment by umara-Nissar** [comment]
Thank you! I will give it  a try and let you know.

**Comment by umara-Nissar** [comment]
@paoloinglese Thank you!! it works fine now. what was the issue? is it something specific to my data?

**Comment by piplus2** [comment]
You're welcome! It was an error with the interpolation of the large images.
