### ISSUE TITLE
How to contact you?

### ISSUE THREAD

**Issue by Philipp-Weigand** [paoloinglese/DESI_MSI_recal#3]
@paoloinglese

Dear Paolo,
I would like to contact you and your co-authors regarding your paper "Deep learning and 3D-DESI imaging reveal the hidden metabolic heterogeneity of cancer" from 2017. The only email address I could online (p.inglese14@imperial.ac.uk ) seems to be offline. How should I contact you via Email?

I apologise for creating this issue with off-topic content.

Kind regards,
Philipp Weigand

**Comment by piplus2** [comment]
Dear Philipp,

I do not work at Imperial anymore.
You can contact me at my personal email address: ***@***.***

Kind regards,

Paolo

**Comment by Philipp-Weigand** [comment]
Dear Paolo,
thanks for your fast response!
The email address you posted is hidden by asterisks.
Github seems to hide it. Do you mean your personal outlook email address?

Kind regards,
Philipp

**Comment by paoloinglese** [comment]
Yes p.inglese at outlook dot com

**Comment by Philipp-Weigand** [comment]
Thank you so much!
